### PR TITLE
Add jsonschema to deps

### PR DESCRIPTION
**Pull request by jacksund**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jacksund** [comment]
@jan-janssen It still looks like there's disagreement between your requirements.txt and the ones listed for conda-forge. Would you update these as you make new releases? I love using matminer, but it's causing a lot of installation issues for my team :cry:

**Comment by jan-janssen** [comment]
@jacksund - I am sorry for the late reply. I am not a matminer developer, just the maintainer of the conda package, but I am fine with updating the dependencies. Still I have a hard time to see how adding an additional dependency should simplify the resolving. Can you try `mamba install -c conda-forge matminer` ? Mamba is a C++ based replacement for the conda dependency solver which provides more intuitive error messages.

**Comment by jacksund** [comment]
@jan-janssen - no worries! Thanks for getting back to me.

And matminer is actually installing just fine (so mamba doesn't print any errors). Matminer installation only gives issues when I list it as a dependency in another conda-forge feedstock. So the error exits in the conda-forge CI, not installing as a user. Here is [an example failed feedstock action](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=433673&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d). The error is here:
image
The error goes away when I added jsonschema as a dependency to my own package.

**Comment by jan-janssen** [comment]
Ok, now I understand - I am going to merge the pull request.

**Comment by jan-janssen** [comment]
@jacksund If you are interested, feel free to add you as contributor to the conda feedstock, then you can update it on your own.

**Comment by jacksund** [comment]
Awesome, thank you! And definitely, I'd love to help out.

**Pull request merged**
